//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBUtils
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orders
    {
        public int Id { get; set; }
        public int Id_User { get; set; }
        public int Id_Candles_Order { get; set; }
        public decimal Price { get; set; }
        public int Id_Status { get; set; }
        public int Id_Address { get; set; }
        public System.DateTime Date { get; set; }
    
        public virtual Candles_Order Candles_Order { get; set; }
        public virtual Order_Address Order_Address { get; set; }
        public virtual Order_Status Order_Status { get; set; }
        public virtual Users Users { get; set; }
    }
}
