//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBUtils
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users_Baskets
    {
        public int Id { get; set; }
        public int Id_User { get; set; }
        public int Id_Candles { get; set; }
        public int Count { get; set; }
    
        public virtual Candles Candles { get; set; }
        public virtual Users Users { get; set; }
    }
}
