//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CandlesCompany
{
    using System;
    using System.Collections.Generic;
    
    public partial class Candles_Order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Candles_Order()
        {
            this.Orders = new HashSet<Orders>();
        }
    
        public int Id { get; set; }
        public int Count { get; set; }
        public Nullable<int> Id_Candles_Sale_Percent { get; set; }
        public int Id_Candles { get; set; }
    
        public virtual Candles Candles { get; set; }
        public virtual Candles_Sale_Percent Candles_Sale_Percent { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Orders> Orders { get; set; }
    }
}
