//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CandlesCompany
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users_Block
    {
        public int Id_Users { get; set; }
        public System.DateTime DateStart { get; set; }
        public int Id_Admin { get; set; }
        public string Reason { get; set; }
    
        public virtual Users Users { get; set; }
        public virtual Users Users1 { get; set; }
    }
}
